--- 
service_name: vfw20
service_description: vfw cnf cds use case
base_chart: base_template
vendor: Michal_vendor
customer: Michal_customer
k8s_rb_profile_name: vfw-cnf-cds-base-profile
k8s_rb_profile_namespace: cnf-namespace-1
region_details:
  region_id: k8s-region-3
  cloud_owner: k8sCloudOwner
  type: k8s
  orchestrator: multicloud
  identity_service: DEFAULT_KEYSTONE
  complex: complexmc
  cloud_version: 2.5
  tenant: k8s-tenant-3
  availability_zone: k8s_availability_zone_1
etc_hosts:
  urls:
    - aai.api.sparky.simpledemo.onap.org
    - cli.api.simpledemo.onap.org
    - msb.api.simpledemo.onap.org
    - msb.api.discovery.simpledemo.onap.org
    - mr.api.simpledemo.onap.org
    - nbi.api.simpledemo.onap.org
    - policy.api.simpledemo.onap.org
    - portal.api.simpledemo.onap.org
    - portal-sdk.simpledemo.onap.org
    - sdc.api.be.simpledemo.onap.org
    - sdc.api.fe.simpledemo.onap.org
    - sdc.api.simpledemo.onap.org
    - sdc.dcae.plugin.simpledemo.onap.org
    - sdc.workflow.plugin.simpledemo.onap.org
    - sdnc.api.simpledemo.onap.org
    - so.api.simpledemo.onap.org
    - vid.api.simpledemo.onap.org
kubeconfig: config/kubeconfig
ONAP_k8s_IP: 10.254.184.254
RANCHER_IP: 10.254.184.254
AAI_user: AAI
AAI_pass: AAI
