---
service_name: "PUT SERVICE NAME HERE"
service_description: "PUT SERVICE DESCRIPTION HERE"
base_chart: "PUT BASE CHART NAME HERE"
vendor: "PUT VENDOR NAME HERE"
customer: "PUT CUSTOMER NAME HERE"
region_details:
  region_id: "PUT REGION ID HERE"
  cloud_owner: "PUT CLOUD OWNER NAME HERE"
  type: k8s
  orchestrator: multicloud
  identity_service: DEFAULT_KEYSTONE
  complex: "PUT COMPLEX NAME HERE"
  cloud_version: 2.5
  tenant: "PUT TENANT NAME HERE"
  availability_zone: "PUT AVAILABILITY ZONE NAME HERE"
etc_hosts:
  urls:
    - aai.api.sparky.simpledemo.onap.org
    - cli.api.simpledemo.onap.org
    - msb.api.discovery.simpledemo.onap.org
    - mr.api.simpledemo.onap.org
    - nbi.api.simpledemo.onap.org
    - policy.api.simpledemo.onap.org
    - portal.api.simpledemo.onap.org
    - portal-sdk.simpledemo.onap.org
    - sdc.api.be.simpledemo.onap.org
    - sdc.api.fe.simpledemo.onap.org
    - sdc.api.simpledemo.onap.org
    - sdc.dcae.plugin.simpledemo.onap.org
    - sdc.workflow.plugin.simpledemo.onap.org
    - sdnc.api.simpledemo.onap.org
    - so.api.simpledemo.onap.org
    - vid.api.simpledemo.onap.org
kubeconfig: config/kubeconfig
ONAP_k8s_IP: "PUT ONE OF ONAP NODE IP ADDRESS HERE"
RANCHER_IP: "PUT ONAP RANCHER/NFS IP ADDRESS HERE"
AAI_user: AAI
AAI_pass: AAI
