---
vendor: Vendor-Michal
customer: Demonstration
service_type: wordpress
complex_id: complexMC
k8s:
  region_id: k8s_region_1
  cloud_owner: k8sCloudOwner
  type: k8s
  orchestrator: multicloud
  identity_service: DEFAULT_KEYSTONE
  complex: complexMC
  cloud_version: 2.5
  tenant: k8s_tenant_1
  availability_zone: k8s_availability_zone_1
openstack:
  cloud_owner: CloudOwner
  region_id: RegionOne
  tenant_name: Integration-SB-00
  tenant_id: 41d6d38489bd40b09ea8a6b6b852dcbd
  check: False
  url: http://10.12.25.2
  user_name: michal_chabiera
  password: password
etc_hosts:
  address: 10.12.5.100
  urls:
    - aai.api.sparky.simpledemo.onap.org
    - cli.api.simpledemo.onap.org
    - msb.api.discovery.simpledemo.onap.org
    - mr.api.simpledemo.onap.org
    - nbi.api.simpledemo.onap.org
    - policy.api.simpledemo.onap.org
    - portal.api.simpledemo.onap.org
    - portal-sdk.simpledemo.onap.org
    - sdc.api.be.simpledemo.onap.org
    - sdc.api.fe.simpledemo.onap.org
    - sdc.api.simpledemo.onap.org
    - sdc.dcae.plugin.simpledemo.onap.org
    - sdc.workflow.plugin.simpledemo.onap.org
    - sdnc.api.simpledemo.onap.org
    - so.api.simpledemo.onap.org
    - vid.api.simpledemo.onap.org
kubeconfig: config/kubeconfig
ONAP_k8s_IP: 10.12.5.100
RANCHER_IP: 10.12.5.150
AAI_user: AAI
AAI_pass: AAI
