- name: Create directory to unzip VSP
  file:
    path: ../csar-prepare/{{service_name}}_CNF
    state: directory
    mode: '0755'
- name: Unzip VSP
  unarchive:
    src: ../csar-prepare/{{service_name}}_CNF.zip
    dest: ../csar-prepare/{{service_name}}_CNF
- name: Create directory to unzip CBA
  file:
    path: ../csar-prepare/{{service_name}}_CNF/CBA
    state: directory
    mode: '0755'
- name: Unzip CBA
  unarchive:
    src: ../csar-prepare/{{service_name}}_CNF/CBA.zip
    dest: ../csar-prepare/{{service_name}}_CNF/CBA
- name: Read TOSCA.meta Template_name
  shell: yq r ../csar-prepare/{{service_name}}_CNF/CBA/TOSCA-Metadata/TOSCA.meta Template-Name
  register: template_name
- name: Read TOSCA.meta Template_name
  shell: yq r ../csar-prepare/{{service_name}}_CNF/CBA/TOSCA-Metadata/TOSCA.meta Template-Version
  register: template_version
