---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Read configuration file
    include_vars: config/config.yml

  - name: Install required packages
    include_tasks: install-packages.yml

  - name: Update etc/hosts
    include_tasks: update-etc-hosts.yml

  - name: Configure region in ONAP
    include_tasks: configure-region.yml


###########################################
####### Configure Region in MariaDB #######
- hosts: RANCHER
  remote_user: root
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: "config/rancher_key"
    template: !unsafe '{{.data.password}}'  
  tasks:
  
  - name: Read configuration file
    include_vars: config/config.yml

  - name: Add region to SO Database
    include_tasks: cloud-registration/add-region-to-SO-db.yml

####################################################
####### Fix SO BPMN endpoint for VNF adapter #######

  - name: Copy script
    copy: src={{playbook_dir}}/script-so-bpmn.sh dest=/tmp mode=0777

  - name: Execute script
    shell: cd && cd / && ./tmp/script-so-bpmn.sh

####################################################
############ Onboard & Instantiate CNF #############

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Read configuration file
    include_vars: config/config.yml

  - name: Run onboarding and instantiation script
    shell: python 3 ../python-onapsdk/script.py "{{vendor}}" "{{customer}}" "{{k8s.cloud_owner}}" "{{k8s.region_id}}" "{{k8s.tenant}}" "{{service_name}}"
