---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: update snap
    shell: snap refresh
    become: yes
  
  - name: install packages
    shell: snap install {{item}}
    with_items:
      - yq
      - jo
    become: yes

  - name: install zip
    shell: apt install zip -y
    become: yes

  - name: Read configuration file
    include_vars: ../global-config.yml

  ###### Wypakowanie wszytkich chartów do katalogu helm ##################
  
  - name: Find all charts names
    find:
      paths: charts/
    register: files_matched

  - name: Prepare charts list
    set_fact:
      file_list: "{{ file_list | default([]) | union([item.path]) }}"
    with_items: "{{ files_matched.files }}"

  - name: Create a helm  directory if it does not exist
    file:
      path: helm
      state: directory
      mode: '0755'

  - name: Unarchive helm packages
    shell: tar xvzf "{{item}}" -C helm
    with_items: "{{ file_list }}"

  ########################################################################

  - name: Create a csar directory if it does not exist
    file:
      path: csar
      state: directory
      mode: '0755'

  - name: Get list of charts in helm directory
    command: ls  helm/
    register: list

  - name: Archive helm and add to csar directory
    shell: cd helm && tar cvzf ../csar/{{item}}_cloudtech_k8s_charts.tgz {{item}}
    with_items: "{{list.stdout_lines}}"

  ###### Generate dummy heat for each cnf ################################

  - name: Create a heat directory if it does not exist
    file:
      path: heat
      state: directory
      mode: '0755'

  - name: Generate YAML files
    shell: cd config/ && ./yaml_generator.sh "{{list.stdout}}" "{{base_chart}}"

  - name: Generate ENV files
    shell: cd config/ && ./env_generator.sh "{{list.stdout}}"

  ################### Generate MANIFEST.json ##############################
  
  - name: Generate MANIFEST.json
    shell: cd config/ && ./manifest_generator.sh "{{service_name}}" "{{service_description}}" "{{list.stdout}}" "{{base_chart}}" > ../heat/MANIFEST.json
  
  ###### Copy heat content to csar directory ##############################

  - name: Copy files from heat/ directory to csar/
    shell: cp heat/* csar/

  ###### Copy CBA to csar directory ##############################

  - name: Copy CBA to csar/
    shell: cp cba/CBA.zip csar/

  ###### ZIP ##############################################################
  - name: make .zip file 
    shell: cd csar/ && zip -r "{{service_name}}"_CNF.zip .

  #########################################################################
  - name: Move zipped file to root directory
    shell: mv csar/{{service_name}}_CNF.zip .
